# Generated by Django 2.1.2 on 2019-08-02 06:05

import blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='文章标题')),
                ('content', models.TextField(verbose_name='正文')),
                ('picture', models.ImageField(default='blog/img/article/default.png', upload_to='', verbose_name='图片')),
                ('first_classify', models.IntegerField(choices=[(0, '生活笔记'), (1, '技术杂谈'), (2, '福利专区')], verbose_name='一级分类')),
                ('second_classify', models.IntegerField(verbose_name='二级分类')),
                ('third_classify', models.IntegerField(verbose_name='三级分类')),
                ('issuedate', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('alterdate', models.DateTimeField(auto_now=True, verbose_name='最近修改')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('browse_count', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('praise', models.IntegerField(default=0, verbose_name='点赞')),
                ('share', models.IntegerField(default=0, verbose_name='分享')),
                ('is_Delete', models.BooleanField(default=True, verbose_name='是否显示')),
                ('synopsis', models.CharField(default='0', max_length=500, verbose_name='大纲')),
                ('comment_num', models.IntegerField(default=0, verbose_name='评论次数')),
                ('reserve3', models.CharField(default='0', max_length=62, verbose_name='保留字段')),
                ('reserve4', models.CharField(default='0', max_length=62, verbose_name='保留字段')),
                ('reserve5', models.CharField(default='0', max_length=62, verbose_name='保留字段')),
            ],
        ),
        migrations.CreateModel(
            name='CommetModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commet', models.CharField(max_length=500, verbose_name='评论内容')),
                ('issuedate', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('alterdate', models.DateTimeField(auto_now=True, verbose_name='最近修改')),
                ('classify', models.IntegerField(null=True, verbose_name='评论类型')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('is_Show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('is_Delete', models.BooleanField(default=True, verbose_name='是否删除')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.ArticleModel', verbose_name='文章')),
            ],
        ),
        migrations.CreateModel(
            name='LikeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('issuedate', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('is_Delete', models.BooleanField(default=True, verbose_name='是否显示')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.ArticleModel', verbose_name='文章')),
            ],
        ),
        migrations.CreateModel(
            name='LinkModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=50, verbose_name='链接地址')),
                ('link_name', models.CharField(max_length=20, verbose_name='链接名称')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('issuedate', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('is_Delete', models.BooleanField(default=True, verbose_name='是否显示')),
            ],
        ),
        migrations.CreateModel(
            name='NavModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nav_name', models.CharField(max_length=6, verbose_name='类别')),
                ('issuedate', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('is_Show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('is_Delete', models.BooleanField(default=True, verbose_name='是否删除')),
                ('Nav_root', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='root_nav', to='blog.NavModel', verbose_name='根')),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='0', max_length=32, verbose_name='昵称')),
                ('password', models.CharField(max_length=256, verbose_name='密码')),
                ('email', models.CharField(max_length=64, unique=True, verbose_name='邮箱地址')),
                ('sex', models.BooleanField(null=True, verbose_name='性别')),
                ('icon', models.ImageField(default='blog/img/user/icon.png', upload_to=blog.models.user_avatar_path, verbose_name='头像')),
                ('is_delete', models.BooleanField(default=True, verbose_name='是否禁用')),
                ('is_activate', models.BooleanField(default=False, verbose_name='是否激活')),
                ('ticket', models.CharField(max_length=30, null=True, verbose_name='session值')),
                ('logintime', models.DateTimeField(auto_now=True, verbose_name='最近登录')),
                ('registertime', models.DateField(auto_now_add=True, verbose_name='注册时间')),
                ('phonenumber', models.CharField(default='0', max_length=62, verbose_name='手机号码')),
                ('reserve2', models.CharField(default='0', max_length=62, verbose_name='保留字段')),
                ('reserve3', models.CharField(default='0', max_length=62, verbose_name='保留字段')),
                ('reserve4', models.CharField(default='0', max_length=62, verbose_name='保留字段')),
                ('reserve5', models.CharField(default='0', max_length=62, verbose_name='保留字段')),
                ('reserve6', models.CharField(default='0', max_length=62, verbose_name='保留字段')),
                ('reserve7', models.CharField(default='0', max_length=62, verbose_name='保留字段')),
            ],
        ),
        migrations.AddField(
            model_name='likemodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.UserModel', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='commetmodel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='author', to='blog.UserModel', verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='commetmodel',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='parent_comment', to='blog.CommetModel', verbose_name='父评论'),
        ),
        migrations.AddField(
            model_name='commetmodel',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='replies', to='blog.UserModel', verbose_name='评论给谁'),
        ),
        migrations.AddField(
            model_name='commetmodel',
            name='root',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='root_comment', to='blog.CommetModel', verbose_name='根评论'),
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.UserModel', verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='nav',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.NavModel', verbose_name='类别'),
        ),
    ]
