# Generated by Django 2.1.2 on 2019-08-02 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlemodel',
            name='first_classify',
        ),
        migrations.RemoveField(
            model_name='articlemodel',
            name='second_classify',
        ),
        migrations.RemoveField(
            model_name='articlemodel',
            name='third_classify',
        ),
    ]
