# Generated by Django 2.1.2 on 2019-08-02 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190802_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlemodel',
            name='nav',
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='nav1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='nav1', to='blog.NavModel', verbose_name='一级类别'),
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='nav2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='nav2', to='blog.NavModel', verbose_name='二级类别'),
        ),
    ]
