# Generated by Django 2.2.3 on 2019-07-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190722_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlemodel',
            name='reserve1',
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='synopsis',
            field=models.CharField(default='0', max_length=62, verbose_name='大纲'),
        ),
    ]
