# Generated by Django 2.1 on 2019-08-08 04:28

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190808_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='icon',
            field=models.ImageField(default='blog/img/icon/icon.png', upload_to=blog.models.user_avatar_path, verbose_name='头像'),
        ),
    ]
