# Generated by Django 2.1.2 on 2019-08-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190802_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='is_show',
            field=models.BooleanField(default=True, verbose_name='是否显示'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='is_Delete',
            field=models.BooleanField(default=True, verbose_name='是否删除'),
        ),
    ]
