# Generated by Django 2.2.3 on 2019-07-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190723_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='synopsis',
            field=models.CharField(default='0', max_length=500, verbose_name='大纲'),
        ),
    ]
