# Generated by Django 2.1.2 on 2019-08-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190802_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='reserve2',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='my_url',
            field=models.CharField(default='/about', max_length=100, verbose_name='URL'),
        ),
    ]
