# Generated by Django 2.1.2 on 2019-07-24 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190723_2339'),
    ]

    operations = [
    ]
