# Generated by Django 2.1.2 on 2019-07-24 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190724_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='picture',
            field=models.ImageField(default='blog/img/article/default.png', upload_to='', verbose_name='图片'),
        ),
    ]
