# Generated by Django 2.1.2 on 2019-08-04 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190803_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='to_examine',
            field=models.BooleanField(default=False, verbose_name='审核'),
        ),
    ]
