# Generated by Django 2.1.2 on 2019-07-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190724_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='first_classify',
            field=models.IntegerField(choices=[(0, '生活笔记'), (1, '技术杂谈'), (2, '福利专区')], verbose_name='一级分类'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='second_classify',
            field=models.IntegerField(choices=[(1, 'C/C++'), (2, 'java'), (3, 'PHP'), (4, 'HTML'), (5, 'Python'), (6, 'JS'), (7, 'Other')], verbose_name='二级分类'),
        ),
    ]
