# Generated by Django 2.2.3 on 2019-07-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190724_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='second_classify',
            field=models.IntegerField(verbose_name='二级分类'),
        ),
    ]
