# Generated by Django 2.1.2 on 2019-07-25 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190724_2018'),
    ]

    operations = [
    ]
