# Generated by Django 2.2.3 on 2019-07-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190725_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=50, verbose_name='链接地址')),
                ('link_name', models.CharField(max_length=20, verbose_name='链接名称')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('issuedate', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('is_Delete', models.BooleanField(default=True, verbose_name='是否显示')),
            ],
        ),
    ]
