# Generated by Django 2.1.2 on 2019-07-26 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_linkmodel'),
    ]

    operations = [
    ]
