# Generated by Django 2.1.2 on 2019-07-26 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190726_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildCommetModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commet', models.CharField(max_length=500, verbose_name='评论内容')),
                ('issuedate', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('is_Show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('is_Delete', models.BooleanField(default=True, verbose_name='是否删除')),
                ('reserve1', models.CharField(default='0', max_length=62, verbose_name='保留字段')),
                ('reserve2', models.CharField(default='0', max_length=62, verbose_name='保留字段')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.UserModel', verbose_name='作者')),
            ],
        ),
        migrations.CreateModel(
            name='CommetModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commet', models.CharField(max_length=500, verbose_name='评论内容')),
                ('issuedate', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('classify', models.IntegerField(null=True, verbose_name='评论类型')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('is_Show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('is_Delete', models.BooleanField(default=True, verbose_name='是否删除')),
                ('reserve1', models.CharField(default='0', max_length=62, verbose_name='保留字段')),
                ('reserve2', models.CharField(default='0', max_length=62, verbose_name='保留字段')),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.ArticleModel', verbose_name='文章')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.UserModel', verbose_name='作者')),
            ],
        ),
        migrations.AddField(
            model_name='childcommetmodel',
            name='father_commet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.CommetModel', verbose_name='父评论'),
        ),
    ]
