# Generated by Django 2.1.2 on 2019-07-26 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20190726_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commetmodel',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.ArticleModel', verbose_name='文章'),
        ),
    ]
