# Generated by Django 2.1.2 on 2019-07-26 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20190726_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childcommetmodel',
            name='author',
        ),
        migrations.RemoveField(
            model_name='childcommetmodel',
            name='father_commet',
        ),
        migrations.RemoveField(
            model_name='commetmodel',
            name='reserve1',
        ),
        migrations.RemoveField(
            model_name='commetmodel',
            name='reserve2',
        ),
        migrations.AddField(
            model_name='commetmodel',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='parent_comment', to='blog.CommetModel', verbose_name='父评论'),
        ),
        migrations.AddField(
            model_name='commetmodel',
            name='reply_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='replies', to='blog.UserModel', verbose_name='评论给谁'),
        ),
        migrations.AddField(
            model_name='commetmodel',
            name='root',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='root_comment', to='blog.CommetModel', verbose_name='根评论'),
        ),
        migrations.AlterField(
            model_name='commetmodel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='author', to='blog.UserModel', verbose_name='作者'),
        ),
        migrations.DeleteModel(
            name='ChildCommetModel',
        ),
    ]
