# Generated by Django 2.1.2 on 2019-07-27 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20190727_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commetmodel',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='parent_comment', to='blog.CommetModel', verbose_name='父评论'),
        ),
        migrations.AlterField(
            model_name='commetmodel',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='replies', to='blog.UserModel', verbose_name='评论给谁'),
        ),
        migrations.AlterField(
            model_name='commetmodel',
            name='root',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='root_comment', to='blog.CommetModel', verbose_name='根评论'),
        ),
    ]
