# Generated by Django 2.1.2 on 2019-07-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20190727_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='commetmodel',
            name='alterdate',
            field=models.DateTimeField(auto_now=True, verbose_name='最近修改'),
        ),
    ]
