# Generated by Django 2.2.3 on 2019-07-28 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_commetmodel_alterdate'),
    ]

    operations = [
    ]
