# Generated by Django 2.1.2 on 2019-07-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_commetmodel_alterdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlemodel',
            name='reserve2',
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='comment_num',
            field=models.IntegerField(default=0, verbose_name='评论次数'),
        ),
    ]
