# Generated by Django 2.1.2 on 2019-07-30 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20190728_2320'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('issuedate', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('is_Delete', models.BooleanField(default=True, verbose_name='是否显示')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.ArticleModel', verbose_name='文章')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.UserModel', verbose_name='用户')),
            ],
        ),
    ]
