# Generated by Django 2.1.2 on 2019-07-30 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_likemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likemodel',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.ArticleModel', verbose_name='文章'),
        ),
    ]
