# Generated by Django 2.2.3 on 2019-07-30 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20190728_1900'),
        ('blog', '0021_auto_20190730_1535'),
    ]

    operations = [
    ]
